default: &default
  adapter: postgresql
  encoding: utf-8
  reconnect: false
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: react_actioncable_development

test:
  <<: *default
  database: react_actioncable_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
